image: docker:latest

services:
  - docker:dind

stages:
  - build and push

build:
  stage: build and push
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t $DOCKER_USERNAME/kormunity_web:latest .
    - docker push $DOCKER_USERNAME/kormunity_web:latest


